### ISSUE TITLE
Fails on my site

### ISSUE THREAD

**Issue by poVoq** [migratetoflarum/lab.migratetoflarum.com#1]
I recently set up a new Flarum page on https://watsan.eu
but the check fails ( acda8269-d2e2-4c0d-bb2f-7d7a26d98f7a) any idea why?

**Comment by clarkwinkelmann** [comment]
Definitely a timeout, but not sure what's causing it.

I'll have to try a scan from my local PC later to diagnose it better.

**Comment by clarkwinkelmann** [comment]
I'm not able to find anything wrong when testing from my development machine... Your server seems to answer reasonably fast.

I'll do some checks from the server itself when I'll have time.

Your forum doesn't have any security issue by the way. You might want to redirect requests from www to apex though (www doesn't resolve currently).

Maybe it's the DNS resolution that's taking more time on the lab. It's possible adding a www record will reduce the duration of the scan and thus fix the issue.

**Comment by poVoq** [comment]
Ok will look into it. Thanks for the update.

**Comment by clarkwinkelmann** [comment]
Are you still experiencing issues ? I just checked the response times again and it looks fine now

![image](https://user-images.githubusercontent.com/5264300/39827402-1c282816-53b8-11e8-906b-77681ea03b5e.png)

Let me know if you still have issues, I'll reopen this :wink:
