### ISSUE TITLE
Some extesion updated is flagged as update needed

### ISSUE THREAD

**Issue by PeopleInside** [migratetoflarum/lab.migratetoflarum.com#24]
Hi, I updated to Flarum 1.0 and all my extensions are updated.
`composer outdated --direct` never show extension that need to be updated but your scanner show it.

When I scan my community community.peopleinside.it some updated extensions are flagged as need update but the version suggested for the update is inferior.

![1](https://user-images.githubusercontent.com/5006150/120778161-532fc200-c526-11eb-8aba-9b9d7a9f3dd7.jpg)

![2](https://user-images.githubusercontent.com/5006150/120778174-56c34900-c526-11eb-8350-3a9a17092be9.jpg)

**Comment by clarkwinkelmann** [comment]
Hi! Thanks for the report.

I have also noticed this issue. Unfortunately there's a bug in my code somewhere and I haven't figured out a solution yet.

It happens to extensions that changed from `x.y.z` to `vx.y.z` format (or vice-versa) for their tags.

I'm using Composer's library to compare the versions but either I'm not using it correctly or Composer's library itself has a bug.
