### ISSUE TITLE
Issue Scanning https://www.joomlart.com/forums/

### ISSUE THREAD

**Issue by Ralkage** [migratetoflarum/lab.migratetoflarum.com#4]
Scanning indicator took a while but ended up error(ing?) out with this GUID just for you as a present ❤️ 🙈

![Scanning STUCK](https://cdn.discordapp.com/attachments/391244820019937280/479353017712246785/unknown.png)

![7a27bc31-f20b-4097-a045-1b90287ff2dc](https://user-images.githubusercontent.com/2059356/44167839-40118600-a09d-11e8-81aa-7e9a40095a36.png)

**Comment by Ralkage** [comment]
10/10 might be due to the fact that it could be either 1). Heavily customized to the point where core files were modified or 2). Something unrelated that I can't answer lol

**Comment by clarkwinkelmann** [comment]
As discussed via Discord this was a job timeout. I can't exactly fix it but I took the following actions:

- Optimized a script that was eating resources on the Lab droplet and probably slowing down scans
- Logged all scan requests even in case of job failure and add them to the error screen, should show if there was a significant response time or if the lab got maybe blacklisted by a firewall
